---

is_debug: true
jwt:
  secret: $3cr3t
lister:
  type: sock
  bind_ip: 0.0.0.0
  port: 1234
mongodb:
  host: localhost
  port: 27017
  database: blog
  auth_db:
  username:
  password:
  collection: users
storage:
  host: localhost
  port: 5432
  database: goblog
  username: postgres
  password: 123
