---

is_debug: true
jwt:
  secret: $3cr3t
lister:
  type: tcp
  bind_ip: 0.0.0.0
  port: 8000
mongodb:
  host: localhost
  port: 27017
  database: blog
  auth_db:
  username:
  password:
  collection: users
storage:
  host: go-blog.c8bslpbkmmhl.ap-northeast-1.rds.amazonaws.com
  port: 5432
  database: go_blog
  username: postgres
  password: postgres
