### Get Users
GET http://0.0.0.0:8000/users/
Accept: application/json


### Get User by id
GET http://0.0.0.0:8000/users/id/?id=1
Accept: application/json


### Get User by username
GET http://0.0.0.0:8000/users/username/?username=artur23
Accept: application/json

### Get User by email
GET http://0.0.0.0:8000/users/email/?email=password
Accept: application/json


### Create User
POST http://0.0.0.0:8000/users/
Accept: application/json

{
"username": "artur",
"email":"admin@gmail.com",
"password":"admin",
"repeat_password":"admin"
}


### Update User
PUT http://0.0.0.0:8000/users/id/?id=73
Accept: application/json

{
  "email": "adsad1",
  "username": "rewr1w",
  "password": "admin"
}

### LOGIN
POST http://0.0.0.0:8000/users/login/?username=admin&password=admin
Accept: application/json
