info:
  title: "BLOG"
  version: "1.0.0.0"
schemes:
  - http
  - https
host: 0.0.0.0:8000
tags:
  - name: Posts
  - name: Users
  - name: Authorization


definitions:
  user:
    type: object
    required:
      - username, email, password
    properties:
      id:
        type: integer
        readOnly: true
        uniqueItems: true
      username:
        type: string
        minLength: 8
        uniqueItems: true
      email:
        type: string
        uniqueItems: true
        format: string@example.com
      password:
        type: string
        minLength: 8
  

  post:
    type: object
    required:
      - title, description, OwnerId
    properties:
      id:
        type: integer
        readOnly: true
        uniqueItems: true
      title:
        type: string
        uniqueItems: true
      description:
        type: string
      ownerId:
        type: integer
  token:
    type: object
    properties:
      token:
        type: string
      refresh_token:
        type: string
  refresh_token:
    type: object
    properties:
      refresh_token:
        type: string

  error:
    type: object
    required:
      - message
    properties:
      message:
        type: string
        readOnly: true
      developer_message:
        type: string
        readOnly: true
      code:
        type: string
        readOnly: true

  internalError:
    description: Internal Server Error

paths:
  "/users/login/":
    post:
      tags:
        - Authorization
      parameters:
        - name: username
          in: query
          type: string
        - name: password
          in: query
          type: string
      responses:
        201:
          description: Status created
          schema:
            $ref: "#/definitions/token"
        400:
          description: Bad request
          schema:
            $ref: "#/definitions/error"
        404:
          description: user not found
          schema:
            $ref: "#/definitions/error"
        500:
          $ref: "#/definitions/internalError"
        default:
          $ref: "#/definitions/error"
    put:
      tags:
        - Authorization
      parameters:
        - name: obj
          in: body
          schema:
            $ref: "#/definitions/refresh_token"
      responses:
        "400":
          description: Bad request
          schema:
            $ref: "#/definitions/error"
        "500":
          description: Internal server
          schema:
            $ref: "#/definitions/internalError"
        "201":
          description: Created
          schema:
            $ref: "#/definitions/token"

  "/users/":
    post:
      tags:
        - Users
      responses:
        201:
          description: created
          schema:
            $ref: "#/definitions/user"
        400:
          description: Bad request
          schema:
            $ref: "#/definitions/error"
        500:
          $ref: "#/definitions/internalError"
      parameters:
        - name: userObj
          in: body
          schema:
            $ref: "#/definitions/user"
    get:
      description: Get list of users

      responses:
        200:
          description: Ok
          schema:
            type: object
            $ref: "#/definitions/user"
        400:
          description: Bad Request
          schema:
            type: object
            $ref: "#/definitions/error"
        "500":
          $ref: "#/definitions/internalError"
      tags:
        - Users
  /users/username/:
    get:
      parameters:
        - name: username
          in: query
          required: true
          type: string
      description: Get User By username
      responses:
        "200":
          description: "Ok"
          schema:
            type: object
            $ref: '#/definitions/user'
        "400":
          description: Bad Request
          schema:
            type: object
            $ref: '#/definitions/error'
        "500":
          $ref: "#/definitions/internalError"
      tags:
        - Users
  /users/email/:
    get:
      parameters:
        - name: email
          in: query
          type: string
          required: true
      description: Get User By Email
      responses:
        "200":
          description: Ok
          schema:
            type: object
            $ref: "#/definitions/user"
        "400":
          description: Bad Request
          schema:
            type: object
            $ref: "#/definitions/error"
        "500":
          $ref: "#/definitions/internalError"
      tags:
        - Users


swagger: "2.0"
